[package]
name = "kv-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
anyhow = "1.0.86"
parking_lot = "0.12.3"
serde = { version = "1.0.203", features = ["derive"] }
tracing = "0.1.40"

[dev-dependencies]
httpc-test = "0.1.9"
reqwest = "0.12.5"
tokio = "1.38.0"
